/**
 * Castle layout — 144 slots.
 *
 * Fortress silhouette with corner towers, perimeter walls, and an interior courtyard.
 *
 * Layer breakdown (top-down; higher layer = more elevated):
 *   Layer 0 —  80 tiles: full castle floor plan (10-col × 8-row rectangle, cols 0–18, rows 0–7)
 *   Layer 1 —  40 tiles: perimeter walls rise — full top row (row 1), left/right tower sides
 *                         (cols 0–2 and 16–18), and full bottom row (row 6); interior courtyard
 *                         (rows 2–5, cols 4–14) remains at ground level only
 *   Layer 2 —  16 tiles: battlement crests on top and bottom wall rows + upper tower sections
 *   Layer 3 —   8 tiles: tallest corner tower caps (cols 0–2 and 16–18, rows 2–3)
 *   Total: 80 + 40 + 16 + 8 = 144
 */

import type { Layout } from "../types";

export const CASTLE_LAYOUT: Layout = [
  { col: 0, row: 0, layer: 0 },
  { col: 2, row: 0, layer: 0 },
  { col: 4, row: 0, layer: 0 },
  { col: 6, row: 0, layer: 0 },
  { col: 8, row: 0, layer: 0 },
  { col: 10, row: 0, layer: 0 },
  { col: 12, row: 0, layer: 0 },
  { col: 14, row: 0, layer: 0 },
  { col: 16, row: 0, layer: 0 },
  { col: 18, row: 0, layer: 0 },
  { col: 0, row: 1, layer: 0 },
  { col: 2, row: 1, layer: 0 },
  { col: 4, row: 1, layer: 0 },
  { col: 6, row: 1, layer: 0 },
  { col: 8, row: 1, layer: 0 },
  { col: 10, row: 1, layer: 0 },
  { col: 12, row: 1, layer: 0 },
  { col: 14, row: 1, layer: 0 },
  { col: 16, row: 1, layer: 0 },
  { col: 18, row: 1, layer: 0 },
  { col: 0, row: 2, layer: 0 },
  { col: 2, row: 2, layer: 0 },
  { col: 4, row: 2, layer: 0 },
  { col: 6, row: 2, layer: 0 },
  { col: 8, row: 2, layer: 0 },
  { col: 10, row: 2, layer: 0 },
  { col: 12, row: 2, layer: 0 },
  { col: 14, row: 2, layer: 0 },
  { col: 16, row: 2, layer: 0 },
  { col: 18, row: 2, layer: 0 },
  { col: 0, row: 3, layer: 0 },
  { col: 2, row: 3, layer: 0 },
  { col: 4, row: 3, layer: 0 },
  { col: 6, row: 3, layer: 0 },
  { col: 8, row: 3, layer: 0 },
  { col: 10, row: 3, layer: 0 },
  { col: 12, row: 3, layer: 0 },
  { col: 14, row: 3, layer: 0 },
  { col: 16, row: 3, layer: 0 },
  { col: 18, row: 3, layer: 0 },
  { col: 0, row: 4, layer: 0 },
  { col: 2, row: 4, layer: 0 },
  { col: 4, row: 4, layer: 0 },
  { col: 6, row: 4, layer: 0 },
  { col: 8, row: 4, layer: 0 },
  { col: 10, row: 4, layer: 0 },
  { col: 12, row: 4, layer: 0 },
  { col: 14, row: 4, layer: 0 },
  { col: 16, row: 4, layer: 0 },
  { col: 18, row: 4, layer: 0 },
  { col: 0, row: 5, layer: 0 },
  { col: 2, row: 5, layer: 0 },
  { col: 4, row: 5, layer: 0 },
  { col: 6, row: 5, layer: 0 },
  { col: 8, row: 5, layer: 0 },
  { col: 10, row: 5, layer: 0 },
  { col: 12, row: 5, layer: 0 },
  { col: 14, row: 5, layer: 0 },
  { col: 16, row: 5, layer: 0 },
  { col: 18, row: 5, layer: 0 },
  { col: 0, row: 6, layer: 0 },
  { col: 2, row: 6, layer: 0 },
  { col: 4, row: 6, layer: 0 },
  { col: 6, row: 6, layer: 0 },
  { col: 8, row: 6, layer: 0 },
  { col: 10, row: 6, layer: 0 },
  { col: 12, row: 6, layer: 0 },
  { col: 14, row: 6, layer: 0 },
  { col: 16, row: 6, layer: 0 },
  { col: 18, row: 6, layer: 0 },
  { col: 0, row: 7, layer: 0 },
  { col: 2, row: 7, layer: 0 },
  { col: 4, row: 7, layer: 0 },
  { col: 6, row: 7, layer: 0 },
  { col: 8, row: 7, layer: 0 },
  { col: 10, row: 7, layer: 0 },
  { col: 12, row: 7, layer: 0 },
  { col: 14, row: 7, layer: 0 },
  { col: 16, row: 7, layer: 0 },
  { col: 18, row: 7, layer: 0 },
  { col: 0, row: 1, layer: 1 },
  { col: 2, row: 1, layer: 1 },
  { col: 4, row: 1, layer: 1 },
  { col: 6, row: 1, layer: 1 },
  { col: 8, row: 1, layer: 1 },
  { col: 10, row: 1, layer: 1 },
  { col: 12, row: 1, layer: 1 },
  { col: 14, row: 1, layer: 1 },
  { col: 16, row: 1, layer: 1 },
  { col: 18, row: 1, layer: 1 },
  { col: 0, row: 2, layer: 1 },
  { col: 2, row: 2, layer: 1 },
  { col: 4, row: 2, layer: 1 },
  { col: 6, row: 2, layer: 1 },
  { col: 12, row: 2, layer: 1 },
  { col: 14, row: 2, layer: 1 },
  { col: 16, row: 2, layer: 1 },
  { col: 18, row: 2, layer: 1 },
  { col: 0, row: 3, layer: 1 },
  { col: 2, row: 3, layer: 1 },
  { col: 16, row: 3, layer: 1 },
  { col: 18, row: 3, layer: 1 },
  { col: 0, row: 4, layer: 1 },
  { col: 2, row: 4, layer: 1 },
  { col: 16, row: 4, layer: 1 },
  { col: 18, row: 4, layer: 1 },
  { col: 0, row: 5, layer: 1 },
  { col: 2, row: 5, layer: 1 },
  { col: 16, row: 5, layer: 1 },
  { col: 18, row: 5, layer: 1 },
  { col: 0, row: 6, layer: 1 },
  { col: 2, row: 6, layer: 1 },
  { col: 4, row: 6, layer: 1 },
  { col: 6, row: 6, layer: 1 },
  { col: 8, row: 6, layer: 1 },
  { col: 10, row: 6, layer: 1 },
  { col: 12, row: 6, layer: 1 },
  { col: 14, row: 6, layer: 1 },
  { col: 16, row: 6, layer: 1 },
  { col: 18, row: 6, layer: 1 },
  { col: 4, row: 1, layer: 2 },
  { col: 6, row: 1, layer: 2 },
  { col: 8, row: 1, layer: 2 },
  { col: 10, row: 1, layer: 2 },
  { col: 0, row: 2, layer: 2 },
  { col: 2, row: 2, layer: 2 },
  { col: 16, row: 2, layer: 2 },
  { col: 18, row: 2, layer: 2 },
  { col: 0, row: 3, layer: 2 },
  { col: 2, row: 3, layer: 2 },
  { col: 16, row: 3, layer: 2 },
  { col: 18, row: 3, layer: 2 },
  { col: 4, row: 6, layer: 2 },
  { col: 6, row: 6, layer: 2 },
  { col: 8, row: 6, layer: 2 },
  { col: 10, row: 6, layer: 2 },
  { col: 0, row: 2, layer: 3 },
  { col: 2, row: 2, layer: 3 },
  { col: 16, row: 2, layer: 3 },
  { col: 18, row: 2, layer: 3 },
  { col: 0, row: 3, layer: 3 },
  { col: 2, row: 3, layer: 3 },
  { col: 16, row: 3, layer: 3 },
  { col: 18, row: 3, layer: 3 },
];

if (CASTLE_LAYOUT.length !== 144) {
  throw new Error(`CASTLE_LAYOUT has ${CASTLE_LAYOUT.length} slots, expected 144`);
}
