/**
 * The player's leaderboard participation on the server (#2624, #2778).
 *
 * The player is this install's `X-Session-ID`, which httpClient injects.
 * Public names are generated by the server; the app never sends name text.
 * Every leaderboard shows the name for all of the player's finished games; a
 * player who hasn't joined appears on no board. `putMe` and `deleteMe` are
 * idempotent, so a replayed sync has no second effect.
 */

import { createGameClient } from "../game/_shared/httpClient";

const request = createGameClient({ apiTag: "players" });

export interface PlayerResponse {
  /** The server-generated public name, or null when not on the leaderboards. */
  readonly display_name: string | null;
}

export const playersApi = {
  getMe: (): Promise<PlayerResponse> => request<PlayerResponse>("/players/me"),

  /** Joins the leaderboards; the server assigns a name (or keeps the current one). */
  putMe: (): Promise<PlayerResponse> => request<PlayerResponse>("/players/me", { method: "PUT" }),

  /** A different generated name. 404 when the player hasn't joined. */
  rerollMe: (): Promise<PlayerResponse> =>
    request<PlayerResponse>("/players/me/reroll", { method: "POST" }),

  /** Leaves every leaderboard (204). */
  deleteMe: (): Promise<void> => request<void>("/players/me", { method: "DELETE" }),
};
