/**
 * The player's leaderboard participation, synced to the server (#2624,
 * #2637, #2778).
 *
 * Launch decision (docs/LEADERBOARD-IDENTITIES.md): public names are
 * generated by the server and players never type one. The player chooses only
 * whether to be on the leaderboards:
 *
 * - **Join** (`joinLeaderboards`): `PUT /players/me`; the server assigns a
 *   generated name, which is stored on the device (`displayName.ts`).
 * - **Leave** (`leaveLeaderboards`): `DELETE /players/me`, and the device
 *   forgets the name.
 * - **Get a new name** (`rerollDisplayName`): `POST /players/me/reroll`.
 *   Online only; it never opts anyone in.
 *
 * Join and leave go through a one-slot queue so they work offline:
 *
 * - **Pending sync.** The intent (`JOIN` or `CLEAR`) is written into one
 *   AsyncStorage slot (`PENDING_KEY`), replacing whatever was there, then sent.
 *   The latest intent wins: a leave after an unsent join sends only the
 *   DELETE, and a join after an unsent leave sends only the PUT. The slot is
 *   cleared only once the server has confirmed that intent, so a failure or an
 *   app kill mid-request keeps it for the next trigger.
 * - **Triggers.** Every join/leave, app launch, and — alongside `SyncWorker` —
 *   reconnect and return to the foreground (`NetworkContext`).
 * - **Launch.** Finishes a stored leave's device clear. Once per install
 *   (`LEGACY_MIGRATED_KEY`), a name this device holds that was never confirmed
 *   for this player id (typed before #2624 shipped, when setting a name was
 *   how a player joined) becomes a join, so that choice is kept — under a
 *   generated name. After that one run, launch never turns a stored name into
 *   a join (e.g. a name left behind by a partly failed "Delete my data" must
 *   not silently re-join the player). Then, with nothing
 *   pending, the device's copy is refreshed from `GET /players/me`: the
 *   server is the source of truth for the name (it replaced typed names in
 *   migration 0030) and for whether the player is on the boards at all.
 * - **Replays are harmless.** Joining again keeps the current name; leaving
 *   again is a no-op. A slot written by an older build that still holds a
 *   typed name is treated as a join: the text itself is never sent.
 *
 * A 400/422 means the server will never accept the request, so it is dropped.
 * Anything else (offline, 5xx, 429, a 404 from a backend without the route
 * yet) keeps it pending.
 *
 * "Delete my data" calls `clearDisplayNameSync` first: it waits for a sync
 * already in flight (which could otherwise put the player back on the boards
 * after the server deleted them) and forgets the pending intent. Only after
 * the server delete succeeds does it call `forgetSyncedDisplayName`.
 *
 * Every local intent and every reroll bumps `localGeneration`, so a
 * `GET /players/me` refresh started before one can't overwrite its result
 * with the stale answer.
 */

import { useEffect, useState } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Sentry from "@sentry/react-native";

import { playersApi } from "../../api/players";
import { clearDisplayName, loadDisplayName, storeAssignedDisplayName } from "./displayName";
import { ApiError } from "./httpClient";
import { getOrCreateSessionId } from "./session";

const PENDING_KEY = "player_display_name_pending_sync";
const SYNCED_KEY = "player_display_name_synced";
/**
 * Set once the one-time legacy-name conversion (see `syncDisplayNameOnLaunch`)
 * has run on this install, whatever its outcome, and by "Delete my data".
 * Never removed: after it is set, no stored name ever turns into a join.
 */
const LEGACY_MIGRATED_KEY = "player_display_name_legacy_migrated";

/** The slot value meaning "join the leaderboards". */
const JOIN = "__join_every_leaderboard__";
/** The slot value meaning "leave every leaderboard" (unchanged since #2637). */
const CLEAR = "__remove_display_name_from_every_leaderboard__";

/** Statuses that mean the server will never accept this request. */
const REJECTED_STATUSES = new Set([400, 422]);

export type LeaderboardSyncPending = "join" | "leave" | null;

interface SyncedMarker {
  session_id: string;
  name: string;
}

async function getItem(key: string): Promise<string | null> {
  try {
    return await AsyncStorage.getItem(key);
  } catch (e) {
    Sentry.captureException(e, { tags: { subsystem: "displayNameSync", op: "read" } });
    return null;
  }
}

async function setItem(key: string, value: string): Promise<boolean> {
  try {
    await AsyncStorage.setItem(key, value);
    return true;
  } catch (e) {
    Sentry.captureException(e, { tags: { subsystem: "displayNameSync", op: "write" } });
    return false;
  }
}

/** Anything but a leave is a join (an older build's slot may hold typed text). */
function pendingKind(slot: string | null | undefined): LeaderboardSyncPending {
  if (slot == null) return null;
  return slot === CLEAR ? "leave" : "join";
}

// In-memory copy of the slot, so screens can show a pending join or leave
// (`useLeaderboardSyncPending`). `undefined` until first read from storage.
let slotMirror: string | null | undefined = undefined;
const slotListeners = new Set<() => void>();

function setSlotMirror(value: string | null): void {
  slotMirror = value;
  slotListeners.forEach((l) => l());
}

// Bumped by every local intent (join, leave, "Delete my data") and by a
// reroll (when it starts and once it has stored its name), so a server answer
// that was requested before it can't overwrite it.
let localGeneration = 0;

/** Clears the slot unless a newer intent replaced `value` meanwhile. */
async function clearPendingIf(value: string): Promise<void> {
  if ((await getItem(PENDING_KEY)) !== value) return;
  try {
    await AsyncStorage.removeItem(PENDING_KEY);
    setSlotMirror(null);
  } catch (e) {
    // Left pending: the next flush replays an idempotent request.
    Sentry.captureException(e, { tags: { subsystem: "displayNameSync", op: "clear" } });
  }
}

async function markSynced(name: string): Promise<void> {
  const marker: SyncedMarker = { session_id: await getOrCreateSessionId(), name };
  await setItem(SYNCED_KEY, JSON.stringify(marker));
}

async function isSynced(name: string): Promise<boolean> {
  const raw = await getItem(SYNCED_KEY);
  if (!raw) return false;
  try {
    const marker = JSON.parse(raw) as Partial<SyncedMarker>;
    return marker.name === name && marker.session_id === (await getOrCreateSessionId());
  } catch {
    return false;
  }
}

// Slot writes, in call order. A flush waits for them, so it never reads a
// slot a join or leave is still writing.
let slotWrites: Promise<unknown> = Promise.resolve();

/** Queues a write of JOIN or CLEAR to the slot; resolves true once it is stored. */
function writeSlot(value: string): Promise<boolean> {
  localGeneration += 1;
  const write = slotWrites.then(async () => {
    const ok = await setItem(PENDING_KEY, value);
    if (ok) setSlotMirror(value);
    return ok;
  });
  slotWrites = write;
  return write;
}

/** One attempt. Resolves true when nothing is left pending; never rejects. */
async function flushOnce(): Promise<boolean> {
  await slotWrites;
  const slot = await getItem(PENDING_KEY);
  if (slot == null) return true;
  const leaving = slot === CLEAR;
  let assigned: string | null = null;
  try {
    if (leaving) {
      await playersApi.deleteMe();
    } else {
      assigned = (await playersApi.putMe()).display_name;
    }
  } catch (e) {
    if (e instanceof ApiError && REJECTED_STATUSES.has(e.status)) {
      await clearPendingIf(slot);
      Sentry.captureMessage("displayNameSync: server rejected the leaderboard request", {
        level: "warning",
        tags: { subsystem: "displayNameSync", status: String(e.status) },
      });
      return (await getItem(PENDING_KEY)) == null;
    }
    Sentry.addBreadcrumb({
      category: "displayNameSync",
      message: `sync failed, kept pending: ${e instanceof Error ? e.message : String(e)}`,
      level: "warning",
    });
    return false;
  }
  // Only the intent still in the slot gets applied: a leave written while
  // this join was in flight must not be undone by the join's answer.
  if ((await getItem(PENDING_KEY)) === slot) {
    if (assigned != null) {
      await storeAssignedDisplayName(assigned);
      await markSynced(assigned);
    }
    await clearPendingIf(slot);
  }
  return (await getItem(PENDING_KEY)) == null;
}

let running: Promise<boolean> | null = null;
let queued: Promise<boolean> | null = null;

function start(): Promise<boolean> {
  const run: Promise<boolean> = flushOnce().finally(() => {
    if (running === run) running = null;
  });
  running = run;
  return run;
}

/**
 * Sends the pending join or leave, if any. Flushes never overlap: a call made
 * during one runs once after it (calls made meanwhile share that run), so the
 * latest intent is always the last one sent, and the returned promise settles
 * only after every flush requested before it. Resolves true when nothing is
 * left pending.
 */
export function flushDisplayNameSync(): Promise<boolean> {
  if (!running) return start();
  if (!queued) {
    const next = (): Promise<boolean> => {
      queued = null;
      return start();
    };
    queued = running.then(next, next);
  }
  return queued;
}

function flushInBackground(op: string): void {
  flushDisplayNameSync().catch((e) => {
    Sentry.captureException(e, { tags: { subsystem: "displayNameSync", op } });
  });
}

/**
 * "Join leaderboards": the player's explicit opt-in. Stores the join in the
 * pending slot and sends it; the server's generated name arrives on the
 * device once it is confirmed (right away online, else on a later trigger).
 * Resolves true once the join is stored; it doesn't wait for the server.
 */
export async function joinLeaderboards(): Promise<boolean> {
  if (!(await writeSlot(JOIN))) return false;
  flushInBackground("join");
  return true;
}

/**
 * "Leave leaderboards" (#2637). First stores the leave (`DELETE
 * /players/me`) in the pending slot, replacing any unsent join, and only
 * then forgets the name on the device, so the DELETE can't be lost:
 *
 * - If the slot write fails, resolves false and changes nothing.
 * - Once the slot holds the leave, it goes out on this flush or the next
 *   trigger (reconnect, foreground, launch), even if the app is killed or the
 *   device clear fails; launch then finishes the device clear.
 *
 * Resolves true once the leave is stored; it doesn't wait for the server.
 */
export async function leaveLeaderboards(): Promise<boolean> {
  if (!(await writeSlot(CLEAR))) return false;
  // A failure here is repaired at launch (`syncDisplayNameOnLaunch`).
  await clearDisplayName();
  flushInBackground("leave");
  return true;
}

export type RerollResult =
  | { status: "rerolled"; name: string }
  /** The server says the player isn't on the leaderboards (404); the device now matches. */
  | { status: "not_joined" }
  /** Offline, a server error, or a pending intent that couldn't be sent. */
  | { status: "failed" };

/**
 * "Get a new name": asks the server for a different generated name. Online
 * only. Sends any pending join or leave first. A reroll never opts anyone in:
 * when the player isn't on the leaderboards it resolves `not_joined` (not a
 * connectivity failure) and forgets the name on the device.
 */
export async function rerollDisplayName(): Promise<RerollResult> {
  if (!(await flushDisplayNameSync())) return { status: "failed" };
  // Invalidates any refresh already in flight: its GET may answer with the
  // name this reroll is about to replace.
  localGeneration += 1;
  const generation = localGeneration;
  try {
    const { display_name: name } = await playersApi.rerollMe();
    if (name == null || generation !== localGeneration) return { status: "failed" };
    await storeAssignedDisplayName(name);
    await markSynced(name);
    // And any refresh started while the POST was in flight.
    localGeneration += 1;
    return { status: "rerolled", name };
  } catch (e) {
    if (e instanceof ApiError && e.status === 404) {
      if (generation === localGeneration) {
        // The server says the player isn't on the leaderboards: match it.
        await clearDisplayName();
      }
      return { status: "not_joined" };
    }
    return { status: "failed" };
  }
}

/**
 * Makes the device's copy match the server's (`GET /players/me`), when no
 * join or leave is waiting to be sent. The server is the source of truth: it
 * replaced typed names with generated ones (#2778) and may have no name for
 * this player at all. Never rejects; a failed read changes nothing.
 */
export async function refreshDisplayNameFromServer(): Promise<void> {
  await slotWrites;
  if ((await getItem(PENDING_KEY)) != null) return;
  const generation = localGeneration;
  let name: string | null;
  try {
    name = (await playersApi.getMe()).display_name;
  } catch {
    return;
  }
  if (generation !== localGeneration || (await getItem(PENDING_KEY)) != null) return;
  if (name == null) {
    await clearDisplayName();
  } else {
    await storeAssignedDisplayName(name);
    await markSynced(name);
  }
}

/**
 * The one-time install migration: a name typed before #2624 (stored, never
 * confirmed for this player id) becomes a join. The flag is written first and
 * the join only if that write succeeded, so this can never run twice; if it
 * can't be recorded, nobody is opted in.
 */
async function migrateLegacyNameOnce(): Promise<void> {
  if ((await getItem(LEGACY_MIGRATED_KEY)) != null) return;
  const name = await loadDisplayName();
  const unsynced = name != null && !(await isSynced(name));
  if (!(await setItem(LEGACY_MIGRATED_KEY, "1"))) return;
  if (unsynced) await writeSlot(JOIN);
}

/**
 * On launch: finish a stored leave's device clear, or (once per install) turn
 * a name the server was never confirmed to hold for this player id into a
 * join; flush whatever is pending; then refresh the device's copy from the
 * server.
 */
export async function syncDisplayNameOnLaunch(): Promise<boolean> {
  await slotWrites;
  const slot = await getItem(PENDING_KEY);
  if (slot === CLEAR) {
    // A leave whose device clear never ran (app killed) or failed. A join
    // after it would have replaced the slot, so any stored name is the old one.
    await clearDisplayName();
  } else if (slot == null) {
    await migrateLegacyNameOnce();
  }
  const settled = await flushDisplayNameSync();
  if (settled) await refreshDisplayNameFromServer();
  return settled;
}

/** The join or leave stored in the slot, not yet confirmed by the server. */
export async function getLeaderboardSyncPending(): Promise<LeaderboardSyncPending> {
  await slotWrites;
  if (slotMirror === undefined) setSlotMirror(await getItem(PENDING_KEY));
  return pendingKind(slotMirror);
}

/** `getLeaderboardSyncPending`, kept current as the slot changes. */
export function useLeaderboardSyncPending(): LeaderboardSyncPending {
  const [pending, setPending] = useState<LeaderboardSyncPending>(pendingKind(slotMirror));
  useEffect(() => {
    let active = true;
    const update = () => {
      if (active) setPending(pendingKind(slotMirror));
    };
    slotListeners.add(update);
    void getLeaderboardSyncPending().then(update);
    return () => {
      active = false;
      slotListeners.delete(update);
    };
  }, []);
  return pending;
}

/**
 * "Delete my data", step one: waits for any sync in flight, then forgets the
 * pending intent and marks the legacy migration done, so no name left on the
 * device can ever turn into a join again. Call it before erasing the server's
 * copy, so no PUT can land after the delete. The settled marker is kept until
 * the server delete has succeeded (`forgetSyncedDisplayName`). Never rejects.
 */
export async function clearDisplayNameSync(): Promise<void> {
  localGeneration += 1;
  await slotWrites;
  await Promise.allSettled([running, queued].filter((p) => p != null));
  await setItem(LEGACY_MIGRATED_KEY, "1");
  try {
    await AsyncStorage.removeItem(PENDING_KEY);
    setSlotMirror(null);
  } catch (e) {
    Sentry.captureException(e, { tags: { subsystem: "displayNameSync", op: "clearAll" } });
  }
}

/**
 * "Delete my data", after the server delete succeeded: forgets which name the
 * server was confirmed to hold. Never rejects.
 */
export async function forgetSyncedDisplayName(): Promise<void> {
  try {
    await AsyncStorage.removeItem(SYNCED_KEY);
  } catch (e) {
    Sentry.captureException(e, { tags: { subsystem: "displayNameSync", op: "forgetSynced" } });
  }
}

/**
 * Test-only: forget in-flight state (AsyncStorage is cleared by the tests).
 * @internal Exported for tests and offline tooling only; no production caller (knip --production, #3126).
 */
export function resetDisplayNameSyncForTests(): void {
  running = null;
  queued = null;
  slotWrites = Promise.resolve();
  slotMirror = undefined;
  localGeneration = 0;
  slotListeners.clear();
}
