"""``/players/me``: the caller's leaderboard participation (#2624, #2778).

The player is the ``X-Session-ID`` (one per install until accounts, #1047).
Public names are generated by the server and never typed by players (launch
decision, docs/LEADERBOARD-IDENTITIES.md):

- ``GET``    the caller's generated name, or ``null`` when not on the boards;
- ``PUT``    join the leaderboards (the explicit opt-in). The server assigns a
             generated name; any request body is ignored, so no client text
             can become public. Joining again keeps the current name;
- ``POST /players/me/reroll``  swap the name for another generated one
             (404 when the caller hasn't joined: a reroll never opts in;
             limited to ``PLAYER_REROLL_RATE_LIMIT`` on top of the write limit);
- ``DELETE`` leave every leaderboard.

Every board shows the name for all of the player's finished games, and a
player who hasn't joined appears on no board. ``PUT`` and ``DELETE`` are
idempotent, so the app's offline sync can replay them safely.
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import Response
from sqlalchemy.exc import SQLAlchemyError

from db.base import DbSession
from limiter import limiter, session_key
from rate_limits import (
    PLAYER_READ_RATE_LIMIT,
    PLAYER_REROLL_RATE_LIMIT,
    PLAYER_WRITE_RATE_LIMIT,
)
from session import get_session_id

from . import service
from .schemas import PlayerResponse

logger = logging.getLogger(__name__)

router = APIRouter()


def _db_error(what: str, detail: str, exc: SQLAlchemyError) -> HTTPException:
    # Class name only: the message carries bound parameters (the session id).
    logger.error("players %s failed: %s", what, type(exc).__name__)
    return HTTPException(status_code=500, detail=detail)


@router.get("/me", response_model=PlayerResponse)
@limiter.limit(PLAYER_READ_RATE_LIMIT, key_func=session_key)
async def get_my_player(request: Request, db: DbSession) -> PlayerResponse:
    """The caller's generated name, or ``{"display_name": null}``."""
    sid = get_session_id(request)
    try:
        name = await service.get_display_name(db, sid)
    except SQLAlchemyError as exc:
        raise _db_error("read", "Failed to load display name.", exc) from exc
    return PlayerResponse(display_name=name)


@router.put("/me", response_model=PlayerResponse)
@limiter.limit(PLAYER_WRITE_RATE_LIMIT, key_func=session_key)
async def put_my_player(request: Request, db: DbSession) -> PlayerResponse:
    """Join the leaderboards; returns the caller's generated name.

    Takes no body: a ``display_name`` sent by an older build is ignored (the
    player still joins, which is what sending a name meant there). Joining
    again returns the same name and writes nothing new.
    """
    sid = get_session_id(request)
    try:
        name = await service.join_leaderboards(db, sid)
        await db.commit()
    except SQLAlchemyError as exc:
        await db.rollback()
        raise _db_error("write", "Failed to join leaderboards.", exc) from exc
    return PlayerResponse(display_name=name)


@router.post("/me/reroll", response_model=PlayerResponse)
@limiter.limit(PLAYER_WRITE_RATE_LIMIT, key_func=session_key)
@limiter.limit(PLAYER_REROLL_RATE_LIMIT, key_func=session_key)
async def reroll_my_player(request: Request, db: DbSession) -> PlayerResponse:
    """Give the caller a different generated name. 404 if they haven't joined."""
    sid = get_session_id(request)
    try:
        name = await service.reroll_display_name(db, sid)
        if name is not None:
            await db.commit()
    except SQLAlchemyError as exc:
        await db.rollback()
        raise _db_error("reroll", "Failed to change display name.", exc) from exc
    if name is None:
        raise HTTPException(status_code=404, detail="Not on the leaderboards.")
    return PlayerResponse(display_name=name)


@router.delete("/me", status_code=204)
@limiter.limit(PLAYER_WRITE_RATE_LIMIT, key_func=session_key)
async def delete_my_player(request: Request, db: DbSession) -> Response:
    """Leave every leaderboard (the generated name is dropped).

    204 whether or not the caller had joined.
    """
    sid = get_session_id(request)
    try:
        await service.clear_display_name(db, sid)
        await db.commit()
    except SQLAlchemyError as exc:
        await db.rollback()
        raise _db_error("delete", "Failed to clear display name.", exc) from exc
    return Response(status_code=204)
