"""replace typed display names with server-generated ones (#2778)

Revision ID: 0030_generated_player_names
Revises: 0029_delete_anon_rows_final
Create Date: 2026-09-30

Launch decision (docs/LEADERBOARD-IDENTITIES.md): public leaderboard names are
generated by the server (``Adjective Animal N``) and players can no longer type
public text. This migrates the players who already had a typed name.

Who stays on the boards: every existing ``players`` row. Under the old model a
row only ever existed because the player deliberately set a name (the Profile
field, the result card's one-time prompt, or a name typed into an older build's
win modal, backfilled by 0027), and setting a name was the opt-in to public
boards. So each of those players keeps their opted-in status, but their typed
text is replaced by a freshly generated name. Nobody without a row is added:
unnamed players stay off every board until they choose to join.

The typed text is not kept anywhere by this migration. (Older rows may still
carry a ``metadata.player_name`` on their own ``games`` rows; that is private
to the player's session and never read by a board.)

Constants are literal, not imported from the app: a migration must keep
meaning what it meant when written (see ``0027_players_display_name``). The
word lists are ``players/generated.py``'s at the time of writing.

Downgrade is a documented no-op: the typed names cannot be restored, and the
generated names are valid names under the previous schema.
"""

import secrets
from collections.abc import Sequence
from datetime import datetime, timezone

import sqlalchemy as sa

from alembic import op

revision: str = "0030_generated_player_names"
down_revision: str | None = "0029_delete_anon_rows_final"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ADJECTIVES = (
    "Breezy", "Bright", "Brave", "Calm", "Cheery", "Chipper", "Clever", "Cosmic", "Cozy",
    "Crisp", "Daring", "Dapper", "Dazzling", "Eager", "Fearless", "Friendly", "Gentle",
    "Gleaming", "Golden", "Happy", "Hardy", "Honest", "Jolly", "Kind", "Lively", "Lucky",
    "Mellow", "Merry", "Mighty", "Nimble", "Noble", "Patient", "Peppy", "Plucky", "Polite",
    "Proud", "Quick", "Quiet", "Radiant", "Rapid", "Shiny", "Silver", "Sleek", "Smart",
    "Snappy", "Speedy", "Spry", "Steady", "Stellar", "Sunny", "Swift", "Tidy", "Trusty",
    "Upbeat", "Valiant", "Vivid", "Warm", "Wise", "Witty", "Zesty",
)  # fmt: skip
_ANIMALS = (
    "Alpaca", "Badger", "Bison", "Bluejay", "Condor", "Crane", "Dolphin", "Eagle", "Falcon",
    "Ferret", "Finch", "Fox", "Gazelle", "Gecko", "Hedgehog", "Heron", "Ibis", "Jaguar",
    "Kestrel", "Koala", "Koi", "Lemur", "Lion", "Llama", "Lynx", "Marmot", "Meerkat",
    "Moose", "Narwhal", "Newt", "Ocelot", "Otter", "Owl", "Panda", "Panther", "Parrot",
    "Pelican", "Penguin", "Puffin", "Quail", "Rabbit", "Raccoon", "Raven", "Robin",
    "Salmon", "Seal", "Sparrow", "Squirrel", "Stork", "Swan", "Tiger", "Toucan", "Turtle",
    "Walrus", "Wombat", "Wren", "Yak", "Zebra",
)  # fmt: skip
_NUMBER_MIN = 10
_NUMBER_MAX = 9999
_BATCH = 1000

_rng = secrets.SystemRandom()

_players = sa.table(
    "players",
    sa.column("session_id", sa.Text()),
    sa.column("display_name", sa.Text()),
    sa.column("updated_at", sa.DateTime(timezone=True)),
)


def generated_name() -> str:
    return (
        f"{_rng.choice(_ADJECTIVES)} {_rng.choice(_ANIMALS)} "
        f"{_rng.randint(_NUMBER_MIN, _NUMBER_MAX)}"
    )


def upgrade() -> None:
    bind = op.get_bind()
    # Fully read before any update runs on the same connection.
    session_ids = [row[0] for row in bind.execute(sa.select(_players.c.session_id))]
    now = datetime.now(timezone.utc)
    stmt = (
        _players.update()
        .where(_players.c.session_id == sa.bindparam("sid"))
        .values(display_name=sa.bindparam("name"), updated_at=now)
    )
    for start in range(0, len(session_ids), _BATCH):
        batch = [
            {"sid": sid, "name": generated_name()} for sid in session_ids[start : start + _BATCH]
        ]
        bind.execute(stmt, batch)


def downgrade() -> None:
    # No-op: typed names are gone for good (see the module docstring).
    pass
